### ISSUE TITLE
Debugger - Cannot read property 'typeClass' of undefined

### ISSUE THREAD

**Issue by kevinbluer** [trufflesuite/vscode-ext#48]
Still working on consistent (or as close as possible) repro steps. In the interim, a few excerpts from 2 different stack traces...

```
TypeError: Cannot read property 'typeClass' of undefined
    at tieWithTable (/Users/bluer/Developer/vscode-ext/node_modules/@truffle/debugger/node_modules/@truffle/codec/lib/format/utils/circularity.ts:18:23)
    at tieWithTable (/Users/bluer/Developer/vscode-ext/node_modules/@truffle/debugger/node_modules/@truffle/codec/lib/format/utils/circularity.ts:30:31)
    at Object.tie (/Users/bluer/Developer/vscode-ext/node_modules/@truffle/debugger/node_modules/@truffle/codec/lib/format/utils/circularity.ts:7:10)
    at Object.decode [as default] (/Users/bluer/Developer/vscode-ext/node_modules/@truffle/debugger/node_modules/@truffle/codec/lib/decode.ts:24:35)
    at decode.next (<anonymous>)
```

```
TypeError: Cannot read properties of undefined (reading 'variables')
rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'variables')
stack trace: TypeError: Cannot read properties of undefined (reading 'variables')
    at map (/Users/tyler/projects/truffle/packages/debugger/lib/data/selectors/index.js:676:54)
    at Array.map (<anonymous>)
    at map (/Users/tyler/projects/truffle/packages/debugger/lib/data/selectors/index.js:675:54)
    at Array.map (<anonymous>)
    at /Users/tyler/projects/truffle/packages/debugger/lib/data/selectors/index.js:658:37
    at /Users/bluer/Developer/vscode-ext/node_modules/reselect/lib/index.js:87:25
    at memoized (/Users/bluer/Developer/vscode-ext/node_modules/reselect/lib/defaultMemoize.js:135:20)
    at /Users/bluer/Developer/vscode-ext/node_modules/reselect/lib/index.js:101:40
    at Function.memoized [as _] (/Users/bluer/Developer/vscode-ext/node_modules/reselect/lib/defaultMemoize.js:135:20)
    at /Users/bluer/Developer/vscode-ext/node_modules/reselect-tree/lib/index.js:85:1
    at /Users/bluer/Developer/vscode-ext/node_modules/reselect/lib/index.js:97:37
    at Function.memoized [as _] (/Users/bluer/Developer/vscode-ext/node_modules/reselect/lib/defaultMemoize.js:135:20)
    at /Users/bluer/Developer/vscode-ext/node_modules/reselect-tree/lib/index.js:85:1
```

**Comment by haltman-at** [comment]
OK I've merged trufflesuite/truffle#5005 to deal with this!

**Comment by kevinbluer** [comment]
FWIW i'm still appearing to get the issue despite the fix 😢 To confirm in case I'm missing something, I've bumped `@truffle/codec` to `0.12.7` and re-running the following steps (including for reference / broader reproducibility):

- `truffle unbox dao`
- `truffle migrate`
- `truffle exec scripts/propose.js` (which will error)
- Debug the txn from the VSCode command palette:

<img width="599" alt="Screen Shot 2022-04-08 at 5 04 32 PM" src="https://user-images.githubusercontent.com/210755/162538037-cd02665f-5669-4510-9a19-bba4cd8413a6.png">

For reference it works fine off the CLI (`truffle debug 0xad41f4...`).

**Comment by haltman-at** [comment]
When you say you're still getting the issue, what exactly do you mean?

**Comment by michaeljohnbennett** [comment]
From my testing as well prior to merge of your PR @haltman-at those code blocks would pass when debugging some of the time. It looks like something else down the stack/elsewhere in the process is crashing/failing and we get back the general error from the redux store that it cannot connect to the RPC client which seems to be the general error we see.

More investigation will need to be done on our side and any pointers on how to get more meaningful debug output from code and debugger would be appreciated, especially inside the sagas code.

**Comment by kevinbluer** [comment]
When attempting to debug (via the following step included above), I get above `Cannot read property 'typeClass' of undefined` in my debug console

**Comment by haltman-at** [comment]
Any stacktrace or anything?

**Comment by kevinbluer** [comment]
Was just doing some digging into this (and about to reply to your above question @haltman-at) when I noticed `session.ready()` wasn't actually being called. Just added as a [temp fix](https://github.com/trufflesuite/vscode-ext/commit/154f7082384cd446092bbfb9a318ba481d7a247b) and it seems to be a lot more consistent. It also seems to correlate with "sporadicalness" of the issue(s) we've been experience. Any take @haltman-at?

**Comment by haltman-at** [comment]
`session.ready` has been a dummy for quite some time.  It isn't necessary anymore, not unless you're using a really old debugger version...
